version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5430:5430"
    restart: always
    networks:
      - mynet
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: bot.Dockerfile
    restart: always
    depends_on:
      - postgres
    stdin_open: true
    expose:
      - 8080
    networks:
      - mynet
volumes:
  dbdata:
networks:
  mynet:
    driver: "bridge"